"""Phase B: turn the JSON tree into Blender asset files.

Materials are created in the current session, written out with
`bpy.data.libraries.write`, then removed again, so building a library never
leaves anything behind in the user's file.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
import json
import os
from pathlib import Path
from typing import Iterator
import uuid

import bpy

from . import node_builder, preview
from .core import extract, material_json, profiles


CATALOG_FILE = "blender_assets.cats.txt"
CATALOG_NAMESPACE = uuid.UUID("6ba7b811-9dad-11d1-80b4-00c04fd430c8")
PACK_PER_CATALOG = "per_catalog"
PACK_PER_MATERIAL = "per_material"
CATALOG_BLEND = "_catalog.blend"


@dataclass
class BuildProgress:
    fraction: float
    phase: str
    message: str = ""
    result: "BuildResult | None" = None


@dataclass
class BuildResult:
    built: int = 0
    failed: int = 0
    files: int = 0
    catalogs: int = 0
    unmapped: dict[str, int] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)


def catalog_uuid(catalog_path: str) -> str:
    """Deterministic id so regenerating the catalog file keeps assignments."""
    return str(uuid.uuid5(CATALOG_NAMESPACE, f"ump:{catalog_path}"))


def write_catalog_file(library_root: Path, catalogs: set[str]) -> int:
    lines = [
        "# This is an Asset Catalog Definition file for Blender.",
        "#",
        "# Generated by Unity Material Browser. Edits are overwritten on rebuild.",
        "",
        "VERSION 1",
        "",
    ]
    expanded: set[str] = set()
    for catalog in catalogs:
        parts = catalog.split("/")
        for index in range(1, len(parts) + 1):
            expanded.add("/".join(parts[:index]))

    for catalog in sorted(expanded):
        simple_name = catalog.replace("/", "-")
        lines.append(f"{catalog_uuid(catalog)}:{catalog}:{simple_name}")

    path = library_root / CATALOG_FILE
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(expanded)


def _asset_tags(document: dict, plan) -> list[str]:
    tags = []
    shader_name = document.get("shader", {}).get("name", "")
    if shader_name:
        tags.append(shader_name.split("/")[-1])
    if plan.workflow and plan.workflow != "unknown":
        tags.append(plan.workflow)
    if plan.profile:
        tags.append(plan.profile)
    roles = {texture.role for texture in plan.textures}
    if profiles.BASE_COLOR in roles:
        tags.append("base color")
    if profiles.NORMAL_MAP in roles:
        tags.append("normal")
    if not plan.textures:
        tags.append("parameters only")
    if plan.blend_mode != profiles.BLEND_OPAQUE:
        tags.append("transparent")
    return tags[:8]


def _mark_asset(material, document: dict, plan) -> None:
    material.asset_mark()
    asset_data = material.asset_data
    if asset_data is None:
        return
    asset_data.catalog_id = catalog_uuid(document.get("material", {}).get("catalog", ""))
    asset_data.description = document.get("source", {}).get("path", "")
    for tag in _asset_tags(document, plan):
        try:
            asset_data.tags.new(tag)
        except (RuntimeError, TypeError):
            pass


def _metadata(document: dict, plan, json_path: str = "") -> dict:
    shader = document.get("shader", {})
    source = document.get("source", {})
    return {
        "ump_json": json_path,
        "ump_unity_guid": source.get("guid", ""),
        "ump_unity_path": source.get("path", ""),
        "ump_source_hash": source.get("hash", ""),
        "ump_shader_guid": shader.get("guid", ""),
        "ump_shader_name": shader.get("name", ""),
        "ump_profile": plan.profile,
        "ump_workflow": plan.workflow,
        "ump_built_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "ump_raw": json.dumps(document.get("material", {}), ensure_ascii=False),
    }


def _preview_path(root: Path, entry: dict) -> Path:
    return root / Path(entry["json"]).with_suffix(".preview.png")


def _purge_material(material) -> None:
    images = node_builder.material_images(material)
    try:
        bpy.data.materials.remove(material)
    except (ReferenceError, RuntimeError):
        pass
    for image in images:
        try:
            if image.users == 0:
                bpy.data.images.remove(image)
        except (ReferenceError, RuntimeError):
            pass


def _write_blend(path: Path, materials: list) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(".blend.tmp")
    bpy.data.libraries.write(
        str(temporary), set(materials), fake_user=True, compress=True
    )
    os.replace(temporary, path)


def build_steps(
    library_root: str | Path,
    *,
    pack_mode: str = PACK_PER_CATALOG,
    generate_previews: bool = True,
    profiles_path: str | Path | None = None,
    only_guids: set[str] | None = None,
    trust_all_tints: bool = False,
) -> Iterator[BuildProgress]:
    root = Path(library_root)
    index = extract.load_index(root)
    if not index:
        raise FileNotFoundError(
            "No extraction index was found. Run Extract before building."
        )

    entries = [
        (guid, entry)
        for guid, entry in index.get("materials", {}).items()
        if only_guids is None or guid in only_guids
    ]
    if not entries:
        raise ValueError("The extraction index contains no materials to build")

    rules = profiles.load_profiles(profiles_path)
    result = BuildResult()
    catalogs: set[str] = set()
    previews_available = generate_previews

    grouped: dict[str, list[tuple[str, dict]]] = {}
    for guid, entry in entries:
        catalogs.add(entry.get("catalog", ""))
        key = entry.get("catalog", "") if pack_mode == PACK_PER_CATALOG else guid
        grouped.setdefault(key, []).append((guid, entry))

    result.catalogs = write_catalog_file(root, catalogs)
    total = max(1, len(grouped))

    for position, (key, group) in enumerate(sorted(grouped.items()), start=1):
        fraction = position / total
        yield BuildProgress(fraction, "BUILD", key or "root")

        created: list = []
        target: Path | None = None
        for guid, entry in group:
            document = material_json.read_document(root / entry["json"])
            if document is None:
                result.failed += 1
                result.warnings.append(f"Unreadable document: {entry.get('json', guid)}")
                continue

            plan = profiles.build_plan(document, None, rules, trust_all_tints)
            for name in plan.unmapped:
                result.unmapped[name] = result.unmapped.get(name, 0) + 1

            material = bpy.data.materials.new(entry.get("asset_name") or entry["name"])
            try:
                node_builder.build_material(
                    material, plan, metadata=_metadata(document, plan, entry["json"])
                )
                _mark_asset(material, document, plan)
            except Exception as error:  # keep building the rest of the library
                result.failed += 1
                result.warnings.append(f"{entry.get('name', guid)}: {error}")
                _purge_material(material)
                continue

            if generate_previews and previews_available:
                rendered = preview.generate(material, _preview_path(root, entry))
                if not rendered:
                    # One failure means the renderer is unavailable here; do not
                    # pay the cost for every remaining material.
                    previews_available = False
                    result.warnings.append(
                        "Previews are unavailable in this Blender session; "
                        "assets were built without thumbnails"
                    )

            created.append(material)
            result.built += 1
            if pack_mode == PACK_PER_MATERIAL:
                target = root / entry["blend"]

        if not created:
            continue

        try:
            if pack_mode == PACK_PER_MATERIAL and target is not None:
                _write_blend(target, created)
                result.files += 1
            else:
                catalog_path = Path(*key.split("/")) if key else Path()
                destination = root / extract.MATERIALS_DIR / catalog_path / CATALOG_BLEND
                _write_blend(destination, created)
                result.files += 1
        except (OSError, RuntimeError) as error:
            result.failed += len(created)
            result.warnings.append(f"{key}: {error}")

        for material in created:
            _purge_material(material)

    if generate_previews:
        preview.cleanup()
    _write_build_report(root, result)
    yield BuildProgress(1.0, "COMPLETE", "Library build finished", result)


def _write_build_report(root: Path, result: BuildResult) -> None:
    path = root / extract.REPORT_NAME
    try:
        report = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        report = {}
    from . import __version__

    report["build"] = {
        "builder_version": __version__,
        "built": result.built,
        "failed": result.failed,
        "files": result.files,
        "catalogs": result.catalogs,
        "built_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "unmapped": sorted(
            ({"property": name, "count": count} for name, count in result.unmapped.items()),
            key=lambda item: -item["count"],
        )[:50],
        "warnings": result.warnings[:50],
    }
    try:
        path.write_text(json.dumps(report, ensure_ascii=False, indent=1), encoding="utf-8")
    except OSError:
        pass


def build(library_root: str | Path, **kwargs) -> BuildResult:
    result = None
    for progress in build_steps(library_root, **kwargs):
        if progress.result is not None:
            result = progress.result
    if result is None:
        raise RuntimeError("Library build produced no result")
    return result
